### ISSUE TITLE
Request for Access to PDW Simulator GitHub Repository

### ISSUE THREAD

**Issue by hyounismsee18seecs** [airex-lab/msdf#1]
Respected Sir, I hope this message finds you well. I am reaching out to kindly request access to the GitHub repository for the PDW simulator. Your work aligns closely with my current research interests, and I believe it would be invaluable for my project. I would greatly appreciate your consideration and any instructions you could provide for accessing or utilizing the simulator.

Thank you for your time and support

**Comment by lokeshmohanty** [comment]
Hi, Please contact us officially through email available on the website (https://airexlab.cds.iisc.ac.in/)
